### ISSUE TITLE
webui: admins unable to delete destinations - error 500

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#168]
Admins are unable to delete a destination.

Steps:

sign in as admin1

create a destination with name "test delete"

delete the recently created destination

<img width="724" alt="screen shot 2017-09-29 at 9 47 25 pm" src="https://user-images.githubusercontent.com/17053096/31041254-17cb2b8a-a560-11e7-94ba-ff00755f70ee.png">

**Comment by iandees** [comment]
https://sentry.io/ragtag/carpools/issues/358318230/

**Comment by iandees** [comment]
This is fixed on staging, please check again.

**Comment by engerm** [comment]
Still getting Internal server error:

https://ragtag-carpool-staging.herokuapp.com/admin/destinations/1/delete

<img width="724" alt="screen shot 2017-09-29 at 11 23 43 pm" src="https://user-images.githubusercontent.com/17053096/31042333-7d766e3c-a573-11e7-8139-7414bf8fdee6.png">

**Comment by engerm** [comment]
Whoops. Correct site now:

https://nomad-staging.ragtag.org/admin/destinations/1/delete

<img width="724" alt="screen shot 2017-09-30 at 12 10 16 am" src="https://user-images.githubusercontent.com/17053096/31042353-d342e912-a573-11e7-9481-852f46f27304.png">

**Comment by iandees** [comment]
https://sentry.io/ragtag/carpools-staging/issues/358348367/

**Comment by iandees** [comment]
Try one more time please. I didn't fix it all the way the first time.

**Comment by engerm** [comment]
An admin is able to delete a destination now

**Comment by engerm** [comment]
Still an issue. Happening again:

https://nomad.ragtag.org/admin/destinations/2645997f-1f77-4d66-9cab-8645376d6cde/delete

**Comment by engerm** [comment]
@iandees It's no longer happening on nomad.ragtag.org. 

I'm assuming there was a merge for this?

Closing issue. Will create a new issue if needed

**Comment by iandees** [comment]
Yep, the merge was referenced at https://github.com/RagtagOpen/nomad/issues/168#ref-pullrequest-261816935
