### ISSUE TITLE
Privacy & Terms: incorrect link in last paragraph

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#391]
The last paragraph has an incorrect type of link for an email address

Should be similar to:
`<a href="mailto:nomad-help@ragtag.org">`

```
MISC. Users complying with prior written licenses may access Nomad thereby until authorization is terminated. Otherwise, this is the exclusive and entire agreement between us. If a TOU term is unenforceable, other terms are unaffected. If TOU translations conflict with the English version, English controls. See Privacy Policy for how we collect, use and share data. If you feel content infringes your rights email nomad-help@ragtag.org.
```

```
<p>MISC. Users complying with prior written licenses may access Nomad thereby until authorization is terminated. Otherwise, this is the exclusive and entire agreement between us. If a TOU term is unenforceable, other terms are unaffected. If TOU translations conflict with the English version, English controls. See Privacy Policy for how we collect, use and share data. If you feel content infringes your rights email <a href="nomad-help@ragtag.org">nomad-help@ragtag.org</a>.</p>
```

<img width="1534" alt="screen shot 2017-10-14 at 11 40 28 pm" src="https://user-images.githubusercontent.com/17053096/31581399-141fa17a-b139-11e7-9846-4763888ae3bc.png">

**Comment by iandees** [comment]
Also fixed in #393.

**Comment by simonl2002** [comment]
This is still still broken. The link is still `https://nomad-staging.ragtag.org/nomad-help@ragtag.org` 'mailto' is needed before the email address

**Comment by schloo** [comment]
@iandees I see you changed this to `config.get('MAIL_DEFAULT_SENDER')` in some places on Privacy & Terms, but this is now showing up as `from@example.com`

**Comment by iandees** [comment]
Fixed in #401.

**Comment by engerm** [comment]
verified.
