### ISSUE TITLE
unauthenticated users should be redirected to login and then be redirected to intended page

### ISSUE THREAD

**Issue by engerm** [RagtagOpen/nomad#504]
This is an issue a customer is experiencing using Safari on an iPhone and iPad:

The link inside an email alerting the user there is passenger requesting a ride is not working. User states when they click the link it does not take them to the page to Allow or Deny the passenger a ride because they are not logged in.

The is a request to have incoming links that require authentication to access them (and the user is not logged in) to be redirected to the login page. Upon login, the user would be redirected to the page they were trying to access.

If a user is already logged and clicks on the link in an email, they should not be redirected to log in. They would go directly to the page.

**Comment by iandees** [comment]
I think this was a configuration error that I fixed in 9c03392.

**Comment by engerm** [comment]
Still not working on staging.

Tested using the following steps:
- log in
- go to My Rides
- Click cancel
- Copy URL. similar to:
> https://nomad-staging.ragtag.org/carpools/55b7357f-7afb-4d6d-a06d-0173ac381fb7/cancel
- log out
- load the above URL
- log in as the same user

Page is not redirected.

**Comment by jillh510** [comment]
Reported on Android as well: As a driver, I got an email that you requested to ride.    1. Clicking on the link from my mobile, I see the information about my carpool but I don't have any way to approve your request.

2. From mobile it's not obvious that I'm not logged in. I then go to login and it doesn't take me back to the screen with information about this carpool.

**Comment by joearasin** [comment]
Replicated on safari-for-web. Overall, it looks like what's happening is that, when you are redirected to a login page, no reference is kept to the referring URL, which means the oauth callback does not know where to redirect.

**Comment by joearasin** [comment]
Thus, we need to, when redirected to login, store the referring URL somewhere (either as a query param that we can pass through as an oauth state parameter, or a cookie or localstorage) so that the oauth redirect can then reroute the user to the right place

**Comment by joearasin** [comment]
I think query param is probably the best approach b/c it doesn't require maintenance of state -- I'll take a swing at implementing it

**Comment by iandees** [comment]
There is already a process to store the next URL in the session and redirect to it on login. We just need to make sure we put the URL in the right spot.

**Comment by joearasin** [comment]
I think there are a few things going on. Flask-login (which we're using) has this functionality built in, but we're not using it.

In addition we have our own session push implemented. I think we should consolidate on managing this state in one place.

**Comment by joearasin** [comment]
ah never mind -- I see USE_SESSION_FOR_NEXT is set

**Comment by joearasin** [comment]
Ok -- figured out (at least a large part of) the problem. The block handler is firing when a user isn't logged in and the redirect in that functionality is breaking the "next" functionality of flask-login

https://github.com/RagtagOpen/nomad/blob/master/app/__init__.py#L114

**Comment by joearasin** [comment]
I think it makes sense to migrate this functionality into the model -- this is already a part of flask-login (see the "is_active" documentation in the [flask-login docs](http://flask-login.readthedocs.io/en/latest/) ), so we do not need our own block handler.

**Comment by tkell** [comment]
Hey hey @joearasin, what's your ETA for this one / can I help at all?  It might cover #482, too

**Comment by joearasin** [comment]
I should be able to knock it out tonight.. I've been fighting with getting flask-login to properly handle a request in testing, in a way that doesn't entail monkeypatching it to the point where it doesn't really integration test.

**Comment by joearasin** [comment]
It is in fact a bug in flask-login -- managed to get a unit test to fail

**Comment by dryan** [comment]
Here's the relevant docs on strong vs basic: https://flask-login.readthedocs.io/en/latest/#session-protection

I can't see any reason not to switch to basic, would love to hear from others.
